### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by rr-** [oczki/lane#20]
- [x] Mockups
- [ ] Implementation

**Comment by oczki** [comment]
![main-page](https://f.cloud.github.com/assets/2924029/2491221/e36076ce-b1df-11e3-913a-7ff27c3d9282.png)

`Log in` and `Register` open popups, just like it is now.
`Learn more` points to /about.
`View sample` points to some example list where we show lane's features.

**Comment by rr-** [comment]
http://english.stackexchange.com/questions/30516/should-i-use-a-comma-before-and-or-or
