### ISSUE TITLE
Additional syntax in cells

### ISSUE THREAD

**Issue by rr-** [oczki/lane#21]
Basic syntax:
- [x] Bold, italics, strike-through, underline
- [x] Hyperlinks

Special syntax:
- [x] Cell classes
- [ ] ~~Column classes (stuff from header cells)~~
- [x] Row classes

**Comment by oczki** [comment]
`[something]` applies span class, making it `<td><span class="something">`.
`[cell:something]` applies cell class, making it `<td class="something">`.
