### ISSUE TITLE
New URL schema

### ISSUE THREAD

**Issue by rr-** [oczki/lane#40]
- [x] Provide table with URL mappings (example: "about page" &rarr; `/about`, `/about/`) - @tehoko 
- [ ] Translate table to code - @rr-

**Comment by oczki** [comment]
All URLs include alternatives with trailing slashes.

| Page | URL |
| --- | --- |
| View default list | `/u/{userName}` |
| View list | `/u/{userName}/{id}` |
| View list as guest | `/u/{userName}/{id}/guest` |
| Log in | `/auth/login` |
| Log out | `/auth/logout` |
| Register | `/auth/register` |
| Reset password | `/auth/reset-password` |
| About | `/about` |
| Help | `/help` |
| Example lane | `/example` |
| Add new list | `/add` |
| Edit list | `/edit/{id}` |
| Export list | `/export/{userName}/{id}` |
| Account settings | `/settings` |
| Delete account | `/delete-account` |
| CSS | `/css/{userName}/{id}` |
| Exec | `/exec` |
