### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by rr-** [oczki/lane#8]
- [x] Mockups
- [ ] Implementation

**Comment by oczki** [comment]
"

### About

Lane stands for _list and nothing else_. It's meant to be a centralized way of organizing various kinds of things - watched movies, completed video games, books on plan-to-read shelf, or files put on external HDDs - without the need of having separate accounts on pages like IMDB, Backloggery, Goodreads, or keeping an Excel file.

Your "lists" don't even have to be proper lists, as with proper styling, you could make them look like an "about me" page. Each list can have its own CSS rules you can modify, and you can use some tags like [b]**bold**[/b] or [red]colors[/red] to easily edit single cells, entire rows or columns. Read more about editing on the `help page`.

`Register` your own account, or `log in` if you already have one.

If you're still not convinced, take a look at an `example lane` and see the features.

Lane is `open source` and released under MIT license.

### Privacy policy

Lane stores all your lists' content along with their settings and custom CSS, and your account credentials - user name, password, plus optional e-mail`&nbsp;`address used to reset your password. If you want, you can tell your browser to remember your credentials, which will set a cookie so you don't need to enter them all the time. Cookies are also used by Google Analytics, which gives us feedback about page views, and Google AdSense that displays ads. You can block accepting cookies in your browser's settings.

Lists can be set as private, which makes them visible to their owner only. Guests or other registered users cannot view your private lists.

You can delete your account at any time.
"

**Comment by rr-** [comment]
We're gonna use Analytics and I'd like to use Adsense too, but that one is up to you
